import type { Metadata } from "next";
import { Montserrat, Squada_One } from "next/font/google";
import "./globals.css";
import { DeviceProvider } from "@/components/DeviceProvider";

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-montserrat',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
});

const squadaOne = Squada_One({
  subsets: ["latin"],
  variable: "--font-squada",
  display: "swap",
  weight: "400", // Squada One has only one weight
});

export const metadata: Metadata = {
  title: "Visva V | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/assets/skill.png" type="image/icon type"></link>
      </head>
      <body className={`${montserrat.variable}  ${squadaOne.variable} antialiased `}>
        <DeviceProvider>
          {children}
        </DeviceProvider>
      </body>
    </html>
  );
}
